/*
  Solved by Michele Riva <ciao@micheleriva.it>
  --
  https://projecteuler.net/problem=2
  --
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

let l = 4e6
let s = 0
let t
let a = 0
let b = 1

while(b < l){
  t = a
  a = b
  b = b + t
  (b & 1) === 0 && (s += b)
}

console.log(s)