/*
  Solved by Michele Riva <ciao@micheleriva.it>
  --
  https://projecteuler.net/problem=2
  --
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

const EUL = () => {

  const even = n => !(n % 2)

  const evenList = []

  const fib = limit => {

    let a = 1
    let b = 2

    for(let i = 0; i < limit; i++){

      a = b,
      b = a+b

      console.log(b)

    }

  }

  fib(10)

}

EUL()

module.exports = {
  algorithm: EUL,
  result: 233168
}