/*
  Solved by Michele Riva <ciao@micheleriva.it>
  --
  https://projecteuler.net/problem=2
  --
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

const EUL = () => {
  let j = 1
  let k = 0
  let t
  let sum = 0

  while(k < 4e6){
    k % 2 > 0 && (sum += k)
    t = j
    j += k
    k = t
  }
  
  return sum
}

module.exports = {
  algorithm: EUL,
  result: 4613732
}